##############################
# Build settings
##############################

[build]
  # Directory to change to before starting a build.
  # This is where we will look for package.json/.nvmrc/etc.
  # If not set, defaults to the root directory.
  base = "/"

## ########################################################################
# Redirect rule to point temporary Netlify URL to preferred domain name
# ========================================================================
# NOTE: This requires the DNS records to be updated to point to Netlify.
[[redirects]]
  from = "https://brootaylorv2.netlify.app/*"
  to = "https://brootaylor.com/:splat"
  status = 301
  force = true

# ########################################################################
# Page redirects
# ========================================================================
# 404 pages
[[redirects]]
  from = "/*"
  to = "/error/404"
  status = 404

[[redirects]]
  from = "/BruceTaylorCV.pdf"
  to = "/assets/docs/cv/BruceTaylorCV.pdf"
  status = 301
  force = true
