# ########################################################################
# Page redirects
# ========================================================================
# 404 pages
[[redirects]]
  from = "/*"
  to = "/error/404"
  status = 404
