## ########################################################################
# Redirect rules to point temporary Netlify URLs to preferred domain names
# ========================================================================
# NOTE: These requires the DNS records to be updated to point to Netlify.
[[redirects]]
  from = "https://brootaylor-eleventy.netlify.app/*"
  to = "https://brootaylor.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://brootaylor-astro.netlify.app/*"
  to = "https://astro.brootaylor.com/:splat"
  status = 301
  force = true

# Alias URLs pointing at primary domain & redirected as well
# ========================================================================
# NOTE: These require the DNS records to be updated to point to Netlify.
[[redirects]]
  from = "https://brootaylor.co.uk/*"
  to = "https://brootaylor.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.brootaylor.co.uk/*"
  to = "https://brootaylor.com/:splat"
  status = 301
  force = true

# ########################################################################
# Page redirects
# ========================================================================
# 404 pages
[[redirects]]
  from = "/*"
  to = "/error/404"
  status = 404
