##############################
# Build settings
##############################

[build]
  command = "echo 'Ok, let us begin this build!' && npm run build && echo 'Build finished, site deployed 🚀'"
  publish = "www"

  # Default site wide settings
  # https://docs.netlify.com/configure-builds/file-based-configuration/#post-processing
  # If skip_processing = true, all other settings are ignored
  [build.processing]
    skip_processing = false
  [build.processing.html]
    pretty_urls = true
  [build.processing.css]
    bundle = false
    minify = false
  [build.processing.js]
    bundle = false
    minify = false
  [build.processing.images]
    compress = true

# Build and deployment config for `production` environment
[context.production]
  command = "npm run deploy:build"
  [context.production.environment]
    GIT_LFS_ENABLED = "true"
    NODE_ENV = "production"
    NODE_VERSION = "12"
    TZ = "Europe/London"


##############################
# Netlify dev server (local)
##############################

# Dev settings: (Used when running local Netlify dev server)
[dev]
  # Declaring port for netlify dev server to use when running the `npm run watch` command
  port = 8888
  command = "npm run watch"
  # Points to directory where `_redirects` file lives
  publish = "src"


##############################
# Plugins
##############################

# 1. Run critical pages through pa11y and fail build if accessibility failures are found.
[[plugins]]
  package = "netlify-plugin-a11y"

    # all inputs are optional, we just show you the defaults below
    [plugins.inputs]

    # required config
    checkPaths = ['/'] # you can give an array of directories or paths to html files, that you want to run a11y checks on

    # # optional config
    # ignoreDirectories = ['/admin']  # explicitly ignore these directories

    # resultMode = "warn" # is "error" by default

    # # Developer only
    # debugMode = true # extra logging for plugin developers

# 2. Optimize images as part of the Netlify build process. Optimizes PNG, JPEG, GIF and SVG file formats.
[[plugins]]
  package = "netlify-plugin-image-optim"

# 3. Is Site Vulnerable Netlify Plugin
[[plugins]]
  package = "netlify-plugin-is-website-vulnerable"

# 4. A Netlify plugin to generate a lighthouse report for every deploy
[[plugins]]
  package = "@netlify/plugin-lighthouse"
    [plugins.inputs]
    # optional, defaults to scanning the current built version of the site
    audit_url = 'https://brootaylor.com'

    # optional, fails build when a category is below a threshold
    [plugins.inputs.thresholds]
      performance = 0.9
      accessibility = 0.9
      best-practices = 0.9
      seo = 0.9
      pwa = 0.9


##############################
# Headers
##############################

# Headers (Global)
[[headers]]
  for = "/*"
  [headers.values]
    # Set the `preload` headers here rather than declaring in the HTML
    Link = '''
      </styles/main.css>; rel=preload; as=style
    '''
    Referrer-Policy = "no-referrer, strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"

# Header for .ico files
[[headers]]
  for = "/*.ico"
  [headers.values]
    Content-Type = "image/x-icon"

# Header for 'normal' JS
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"

# Header for ES6 Modules
[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"

# Header for JSON
[[headers]]
  for = "/*.json"
  [headers.values]
    Content-Type = "application/json; charset=utf-8"


##############################
# Redirects
##############################

## ########################################################################
# Redirect rule to point temporary Netlify URL to preferred domain name
# ========================================================================
# NOTE: This requires the DNS records to be updated to point to Netlify.
[[redirects]]
  from = "https://brootaylorv2.netlify.app/*"
  to = "https://brootaylor.com/:splat"
  status = 301
  force = true

# Alias URLs pointing at primary domain & redirected as well
# ========================================================================
# NOTE: These require the DNS records to be updated to point to Netlify.
[[redirects]]
  from = "https://brootaylor.co.uk/*"
  to = "https://brootaylor.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.brootaylor.co.uk/*"
  to = "https://brootaylor.com/:splat"
  status = 301
  force = true

# ########################################################################
# Site-specific page redirects
# ========================================================================
# 404 pages
[[redirects]]
  from = "/*"
  to = "/error/404"
  status = 404

# ========================================================================
# NOTE: Using `_redirects-production.njk` file - (compiles to `_redirects`) - to handle page level redirects cause doesn't seem to work properly in this .toml config file for some reason.
# ========================================================================
