##############################
# Build settings
##############################

[build]
  command = "npm run build"
  publish = "dist"


##############################
# Netlify dev server (local)
##############################

# Dev settings: (Used when running local Netlify dev server)
[dev]
  command = "npm run dev"
  # Declaring port for netlify dev server to use when running the `npm run dev` command
  port = 8889


##############################
# Redirects
##############################

## ########################################################################
# Redirect rule to point temporary Netlify URL to preferred domain name
# ========================================================================
# NOTE: This requires the DNS records to be updated to point to Netlify.
[[redirects]]
  from = "https://brootaylor-astro.netlify.app/*"
  to = "https://astro.brootaylor.com/:splat"
  status = 301
  force = true

## more info on configuring this file: https://docs.netlify.com/configure-builds/file-based-configuration/
