module.exports = {
  name: 'Bruce Taylor',
  short_name: 'BWT',
  metaTitle: 'Bruce Taylor',
  metaDescription: 'I\'m Bruce Taylor, a Front End Web Designer & Developer living in Crawley, West Sussex, UK.',
  metaImage: '/assets/images/common/logo.png',
  metaImageAlt: 'Site logo for Bruce Taylor',
  lang: 'en-gb',
  start_url: '/',
  display: 'standalone',
  rootUrl: process.env.URL || '',
  environment: process.env.ELEVENTY_ENV,
  logo: '/assets/images/common/avios-logo.png',
  theme_color: '#212227',
  accent_color: '#20e',
  background_color: '#fff',
  favicon: '/assets/ico/favicon.ico',
  icon: '/assets/ico/apple-touch-icon.png',
  icon_192: '/assets/ico/android-chrome-192x192.png',
  icon_384: '/assets/ico/android-chrome-384x384.png',
  icon_512: '/assets/ico/android-chrome-512x512.png',
  ms_tile: '/assets/ico/mstile-150x150.png',
  twitter: '@brootaylor',
  year: '2020',
  author: {
    name: 'Bruce Taylor',
    url: 'https://brootaylor.com'
  },
};

