backend:
  name: git-gateway
  branch: develop

publish_mode: editorial_workflow
media_folder: "src/assets/images/uploads"
public_folder: "/assets/images/uploads"

collections:
  - name: "writing"
    label: "Writing"
    folder: "src/_content/writing"
    slug: "{{ date | dateOnly }}/{{ page.fileSlug }}"
    preview_path: "/writing/{{ date | dateOnly }}/{{ page.fileSlug }}.html"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/writing.njk" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Summary", name: "summary", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "" }
      - { label: "Tags", name: "tags", widget: "list", allow_add: true }
      - { label: "Body", name: "body", widget: "markdown" }



