# Config for how content is created, modified and previewed using the Netlify CMS GUI.
# ====================================================================================

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow # Ensures content goes through workflow first, ("Drafts" --> "In Review" --> "Ready"), before being published
media_folder: "src/assets/images/uploads" # Media files will be stored in the repo under src/assets/images/uploads
public_folder: "/assets/images/uploads" # The src attribute for uploaded media will begin with /assets/images/uploads

collections:
  - name: "writing"
    label: "Writing"
    folder: "src/_content/writing"
    slug: "{{slug}}"
    preview_path: "writing/{{year}}-{{month}}-{{day}}/{{slug}}" # A deployment preview URL. Allows a preview of the URL that's not on the production domain
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Meta Description", name: "summary", description: "This populates the page's meta decsription field", widget: "string"}
      - {label: "Lead", name: "lead", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Updated Date", name: "updated", widget: "datetime"}
      - label: "Location"
        name: "location"
        widget: "object"
        collapsed: true
        fields:
          - {label: "locality", name: "locality", widget: "string", default: "Crawley"}
          - {label: "Country", name: "country-name", widget: "string", default: "United Kingdom"}
      - {label: "Categories", name: "category", widget: "list", allow_add: true}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "notes"
    label: "Notes"
    folder: "src/_content/notes"
    identifier_field: "file-name" # Changing `identifier_field` to `file-name` so that default `title` isn't used in this instance
    slug: "{{file-name}}"
    preview_path: "notes/{{year}}-{{month}}-{{day}}/note_{{slug}}" # A deployment preview URL. Allows a preview of the URL that's not on the production domain
    create: true
    fields:
      - {label: "File Name", name: "file-name", widget: "string"}
      - {label: "Meta Description", name: "summary", description: "This populates the page's meta decsription field", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Updated Date", name: "updated", widget: "datetime"}
      - label: "Location"
        name: "location"
        widget: "object"
        collapsed: true
        fields:
          - {label: "locality", name: "locality", widget: "string", default: "Crawley"}
          - {label: "Country", name: "country-name", widget: "string", default: "United Kingdom"}
      - {label: "Categories", name: "category", widget: "list", allow_add: true}
      - {label: "Body", name: "body", widget: "markdown"}



